% LaTeX file for Chapter 03





\chapter{Results}


\section{Example from Carter}

The clinical trial aims to assess the palliative effects of radiation therapy and esophageal stents in terminal esophageal cancer patients. It plans to enroll 324 participants, with an expected accrual rate of 18 subjects per month (or about 0.591 per day) across multiple centers. A simple estimate suggests that recruitment will take 18 months or 548 days ($324/18$), assuming a constant enrollment rate. However, the proposed method in the study evaluates whether this estimate is realistic and feasible using Monte Carlo (MC) simulations \citep{carter2004application}.

Before running simulations, it's assumed that participant arrivals follow a Poisson process with a constant rate over 18 months (548 days). This results in a Poisson distribution with a mean of $\lambda = 0.591 \cdot 548 = 324$ participants, matching the trial's target. This approach allows assigning probabilities to different recruitment durations, helping assess how likely it is to meet the enrollment goal within the planned timeframe.


\section{Pros and cons of Monte Carlo's simulations}

Carter suggests using Monte Carlo simulations, independent and identically distributed realizations of random variables. One clear advantage of MC simulations is their flexibility, as we can simulate any distribution we want. However, we must consider the following when we use MC simulations instead of the exact probability distribution:

\begin{itemize}
\item $M$, the number of simulations
\item Set a seed for computational reproducibility
\item Monte Carlo standard errors (MCse) of estimates based on MC simulations
\item Pseudo random numbers generated in R rely in the assumption that these pseudo random numbers are close to the true realizations of random variables \citep{held2014applied}
\end{itemize}


\section{Important questions when forecasting recruitment at the design-stage of a study}

By normal approximation to the Poisson distribution $C(t)\sim \textrm{N}(\mu=\lambda t, \sigma^2=(\lambda t)^2)$, we know that the probability of recruiting the desired $N$ participants is 0.5. Which means that the study has 50\% chance of obtaining the desired sample size in the suggested $T$ \citep{carter2004application}. We would also be assuming that the recruitment rate is constant over time.

In fact, we do not need normal approximation to see this. This can be shown with the Poisson distribution itself, see Tables \ref{tab:mcsec} and \ref{tab:mcset}. We only need to specify the probability above $\lambda t$, for example, $0.9$. For large $\lambda$, 50\% of the distribution will be below $\lambda t$. With $\lambda < 1$ this is no longer the case. 

This raises two questions which will be answered throughout this Master Thesis:
\begin{enumerate}
\item \textbf{Rate:} If $T$ is fixed, what does the expected rate $\lambda$ need to be to achieve a certain certainty of enrolling the total sample size $N$ within the time frame $T$?
\item \textbf{Time:} Given a certain rate $\lambda$, how long should the recruitment period $T$ be planned to give a confidence above 50\% of recruiting the total sample size $N$? In Machine Learning, this confidence is aimed at 80\%. In \cite{carter2004application}, at 90\%.
\end{enumerate}


\section{Counts: Comparison exact vs Monte Carlo simulations}

Carter raises two important questions, enumerated in the previous section \citep{carter2004application, carter2005practical}. He suggests the use of Monte Carlo (MC) simulations for counts. Here we investigate the accuracy of his MC simulations by comparing them with exact distributions for accrual of counts introduced in Chapter 3.

As we saw in the previous chapter we can model the counts taking into account only the aleatory uncertainty using $C(T)\sim \textrm{Po}(\lambda T)$ with $T=548$. Or, more realistically, take into consideration the fluctuation of $\Lambda$ over time using $C(T)\sim \textrm{Po}(\Lambda T)$ with $\Lambda\sim \textrm{G}(\alpha, \beta)$.

Figures \ref{fig:3_1} and \ref{fig:3_2} show the comparison between the theoretical models for counts discussed in Chapter 3 and their respective MC simulations. In Figures \ref{fig:3_1} and \ref{fig:3_2}, we can see how we need at least $M=10^5$ MC results of simulations to converge to the theoretical probability distribution discussed in Chapter 3. \cite{carter2004application} uses $M = 10^3$.


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
set.seed(2025)

M <- 10^5
t <- seq(1, 550, 1)
lambda <- 0.591

cval_cum_matrix <- matrix(NA, nrow = M, ncol = length(t))

for (i in 1:M) {
	cval <- rpois(length(t), lambda)
	cval_cum_matrix[i, ] <- cumsum(cval)
}

final_counts <- cval_cum_matrix[, length(t)]
\end{verbatim}
\end{kframe}
\end{knitrout}


\begin{figure}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/ch03_figunnamed-chunk-1-1} 
\end{knitrout}
  \caption{Comparison of theoretical smoothed Probability Mass Function (PMF) of Poisson model for counts with $\lambda = 0.591$ for accrual at time $T=548$ and Monte Carlo (MC) simulations with $M=10^5$.}
  \label{fig:3_1}
\end{figure}



\begin{figure}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/ch03_figunnamed-chunk-2-1} 
\end{knitrout}
\caption{Comparison of theoretical smoothed Probability Mass Function (PMF) of Poisson-Gamma model for counts with $\alpha = 32.4$ and $\beta = 54.8$ for accrual at time $T=548$, and Monte Carlo (MC) simulations with $M=10^5$.}
\label{fig:3_2}
\end{figure}

\begin{table}[h!]
\centering
\begin{tabular}{cccc}
 \textbf{Model} & \textbf{Estimated Probabilty} & \textbf{MCse} & \textbf{Exact Probability} \\
\hline
\hline
 $C(T)\sim\textrm{Po}(\lambda T)$ & $\textrm{P}(C(T)\geq 324) = 0.508$ & 0.713 & 0.508 \\
 $C(T)\sim\textrm{PoG}(T, \alpha, \beta)$ & $\textrm{P}(C(T)\geq 324) = 0.483$ & 0.695 & 0.501 
\end{tabular}
\caption{Probability estimates based on Monte Carlo simulations, their respective Monte Carlo standard errors (MCse) and exact probability computations for processes considered in modeling counts where the waiting time is fixed as $T = 548$,  $\lambda = 0.591$, $\alpha = 32.4$ and $\beta = 54.8$.}
\label{tab:mcsec}
\end{table}


\section{Time: Comparison exact vs Monte Carlo simulations}


As we saw in the previous chapter we can model the waiting time to accrue $N = 324$ objects when unit-time recruitment rate is $\lambda = 0.591$ taking into account only aleatory uncertainty with $T(N)\sim \textrm{Erlang}(N,\lambda)$. Or, taking into account both aleatory and epistemic uncertainty with $T(N)\sim\textrm{G}(N, \Lambda)$ where $\Lambda\sim \textrm{G}(\alpha,\beta)$.


Figures \ref{fig:3_3} and \ref{fig:3_4} show the comparison between the theoretical models for waiting time discussed in Chapter 4 and their respective MC simulations. In Figures \ref{fig:3_3} and \ref{fig:3_4}, we can see how we need at least $M=10^5$ MC results of simulations converge to the theoretical probability distribution discussed in Chapter 4.


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
M <- 10^5
Ctarget <- 324
lambda <- 0.591

alpha <- 32.4
beta <- 54.8

simulate_time_to_threshold_Erlang <- function(MM, CC, ll, rseed=265735) {
  set.seed(rseed)
  timeerlang <- rgamma(n=MM, shape = CC, rate = ll)
  return(timeerlang)
}

time_erlang <- simulate_time_to_threshold_Erlang(MM=M, CC=Ctarget, ll=lambda, rseed=265735)

simulate_time_to_threshold_GG <- function(MM, CC, aa, bb, rseed=265735) {
  set.seed(rseed)
  timegg <- rep(0, MM)
  lambdar <- rgamma(n=MM, shape = aa, rate = bb)
  for (i in 1:MM){
    timegg[i] <- rgamma(n=1, shape = CC, rate = lambdar[i])
  }
  return(timegg)
}

timegg <- simulate_time_to_threshold_GG(MM=M, CC=Ctarget, aa=alpha, bb=beta) 
\end{verbatim}
\end{kframe}
\end{knitrout}

\begin{figure}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/ch03_figunnamed-chunk-3-1} 
\end{knitrout}
\caption{Comparison of theoretical density function of Erlang model for the waiting time until $N = 324$ subjects are accrued with recruitment rate $\lambda = 0.591$ and Monte Carlo (MC) simulations with $M=10^5$.}
\label{fig:3_3}
\end{figure}


\begin{figure}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/ch03_figunnamed-chunk-4-1} 
\end{knitrout}
\caption{Comparison of theoretical density function of Gamma-Gamma model for waiting time with parameters $N=324$, $\alpha = 32.4$ and $\beta = 54.8$ and Monte Carlo (MC) simulations with $M=10^5$.}
\label{fig:3_4}
\end{figure}






\begin{table}[h!]
\centering
\begin{tabular}{cccc}
 \textbf{Model} & \textbf{Estimated Probabilty} & \textbf{MCse} & \textbf{Exact Probability} \\
\hline
\hline
 $T(N)\sim\textrm{G}(N, \lambda)$& $\textrm{P}(T(N)\geq 548) = 0.497$ & 0.705 & 0.496\\
$T(N)\sim\textrm{GG}(N, \alpha, \beta)$ & $\textrm{P}(T(N)\geq 548) = 0.518$ & 0.72 & 0.52
\end{tabular}
\caption{Probability estimates based on Monte Carlo simulations, their respective Monte Carlo standard errors (MCse) and exact probability computations for all processes considered in modeling time where the sample size is fixed to be $N = 324$,  $\lambda = 0.591$, $\alpha = 32.4$ and $\beta =54.8$.}
\label{tab:mcset}
\end{table}



Small number of simulations (up to $M=10^3$) from \cite{carter2004application} gives him inaccurate estimate of days (580), when the exact using the Erlang distribution gives  588 to have 90\% chance of accruing $N=324$ subjects with a recruitment rate of $\lambda=0.591$.

Moreover, if we wish to be more realistic in the uncertainty our model takes into consideration and choose the Gamma-Gamma distribution, 707 days would be required to have a 90\% chance of accruing the desired sample size. 

In Tables \ref{tab:mcsec} and \ref{tab:mcset} we illustrate how, indeed, by using the expected accrual without taking into consideration any uncertainty we have roughly a 50\% chance of accruing the desired sample size in the established time-frame \citep{carter2004application}.


